spring:
    application:
        name: msg-app
    datasource:
      url: jdbc:mysql://localhost:3306/messaging_app?createDatabaseIfNotExist=true
      username: root
      password: gespoly
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    springdoc:
      swagger-ui:
        path: /swagger
    server:
      port: 8081
    logging:
      level:
        root: DEBUG
